
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##HHH
    password: HHH
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000KB
      max-request-size: 5000KB

mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.example.boardPrac2.dto.**

