

server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##HHH
    password: HHH


mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.example.boardPrac2.dto.**

