server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##HHH
    password: HHH
    driver-class-name: oracle.jdbc.driver.OracleDriver
  profiles:
    active: local


mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: board.mybatis.dto.**



